global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hcp-consensus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:26660', 'host.docker.internal:26661', 'host.docker.internal:26662', 'host.docker.internal:26663']
    metrics_path: /metrics

  - job_name: 'hcp-gateway'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /performance/metrics

  - job_name: 'hcp-server'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: /metrics
